### ISSUE TITLE
Intentions are not working properly for goals with arguments

### ISSUE THREAD

**Issue by knisht** [JetBrains/intellij-arend#304] opened 2021-09-11 19:34 UTC
At least, "Replace with constructors" is among them.
![Peek 2021-09-11 22-29](https://user-images.githubusercontent.com/36202647/132959357-431deda2-f3c7-459c-a43d-d6de14443b43.gif)

**Comment by valis** [comment] 2021-09-11 19:46
Probably a duplicate of #299.

**Closed** 2023-07-24 18:18 UTC
